# Generated by Django 5.2.1 on 2025-05-26 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('travel_from', models.CharField(blank=True, max_length=100)),
                ('package_id', models.CharField(blank=True, choices=[('Everest', 'Everest Region'), ('Annapurna', 'Annapurna Region')], max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('surname', models.CharField(blank=True, max_length=100)),
                ('given_name', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('dob', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=100)),
                ('passport_no', models.CharField(blank=True, max_length=50)),
                ('passport_image_path', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_image_path', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travel_bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
