# Generated by Django 5.2.1 on 2025-06-17 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(max_length=20)),
                ('nationality', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('zip', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=100)),
                ('perma_address', models.TextField(blank=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('vat_pan', models.CharField(blank=True, max_length=50)),
                ('nid_citizen', models.CharField(blank=True, max_length=50)),
                ('pp_number', models.CharField(blank=True, max_length=50)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('unique_id', models.CharField(max_length=100, unique=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to=settings.AUTH_USER_MODEL)),
                ('billed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billed_clients', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_comments', models.TextField(blank=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='TrackingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_from', models.CharField(max_length=100)),
                ('emergency_contact', models.CharField(max_length=100)),
                ('package', models.CharField(max_length=100)),
                ('travel_start_date', models.DateField(blank=True, null=True)),
                ('travel_end_date', models.DateField(blank=True, null=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='UploadedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('passport', 'Passport'), ('kyc', 'KYC'), ('citizen', 'Citizen Card'), ('photo', 'Photo')], max_length=20)),
                ('file', models.FileField(upload_to='uploads/')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='InternetDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_or_mac', models.CharField(max_length=100)),
                ('enable', models.BooleanField(default=True)),
                ('mac_user', models.BooleanField(default=False)),
                ('password', models.CharField(blank=True, max_length=128)),
                ('mac_address_of_cm', models.CharField(blank=True, max_length=100)),
                ('simultaneous_use', models.PositiveIntegerField(default=1)),
                ('download_limit', models.BigIntegerField(default=0)),
                ('upload_limit', models.BigIntegerField(default=0)),
                ('total_limit', models.BigIntegerField(default=0)),
                ('account_expiry_date', models.DateField(blank=True, null=True)),
                ('radius_comments', models.TextField(blank=True)),
                ('radius_attribute', models.TextField(blank=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('service_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.serviceplan')),
                ('user_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.usergroup')),
            ],
        ),
    ]
