# Generated by Django 5.2.1 on 2025-06-17 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='pp_number',
            new_name='passport_number',
        ),
    ]
