# Generated by Django 5.2.1 on 2025-06-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_remove_client_billed_by_remove_client_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
