# Generated by Django 5.2.1 on 2025-06-24 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_alter_address_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internetdetails',
            old_name='market_by',
            new_name='marketed_by',
        ),
    ]
