# Generated by Django 5.2.1 on 2025-06-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_rename_market_by_internetdetails_marketed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='unique_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
