# Generated by Django 5.2.1 on 2025-06-24 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_alter_client_unique_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='internetdetails',
            name='billed_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='internetdetails',
            name='marketed_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marketed_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
