# Generated by Django 5.2.1 on 2025-07-01 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_client_extra_field_1_client_extra_field_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internetdetails',
            name='extra_field_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internetdetails',
            name='extra_field_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
