# Generated by Django 5.2.1 on 2025-07-10 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_internetdetails_extra_field_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internetdetails',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('unverified', 'Unverified'), ('foc', 'FOC'), ('priv', 'Priv')], max_length=20),
        ),
    ]
